// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/tutorial/message.proto

package com.zq.kyb.core.model;

public final class ProtoMessage {
  private ProtoMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string _id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string _id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string _id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required .tutorial.message.MsgType type = 2;</code>
     */
    boolean hasType();
    /**
     * <code>required .tutorial.message.MsgType type = 2;</code>
     */
    com.zq.kyb.core.model.ProtoMessage.message.MsgType getType();

    /**
     * <code>optional string creator = 3;</code>
     */
    boolean hasCreator();
    /**
     * <code>optional string creator = 3;</code>
     */
    java.lang.String getCreator();
    /**
     * <code>optional string creator = 3;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    /**
     * <code>optional int64 createTime = 4;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>optional int64 createTime = 4;</code>
     */
    long getCreateTime();

    /**
     * <code>required string actionPath = 5;</code>
     */
    boolean hasActionPath();
    /**
     * <code>required string actionPath = 5;</code>
     */
    java.lang.String getActionPath();
    /**
     * <code>required string actionPath = 5;</code>
     */
    com.google.protobuf.ByteString
        getActionPathBytes();

    /**
     * <code>optional string tokenStr = 6;</code>
     */
    boolean hasTokenStr();
    /**
     * <code>optional string tokenStr = 6;</code>
     */
    java.lang.String getTokenStr();
    /**
     * <code>optional string tokenStr = 6;</code>
     */
    com.google.protobuf.ByteString
        getTokenStrBytes();

    /**
     * <code>required int32 code = 7;</code>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 7;</code>
     */
    int getCode();

    /**
     * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
     */
    boolean hasReqContentType();
    /**
     * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
     */
    com.zq.kyb.core.model.ProtoMessage.message.MsgFormat getReqContentType();

    /**
     * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
     */
    boolean hasRespContentType();
    /**
     * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
     */
    com.zq.kyb.core.model.ProtoMessage.message.MsgFormat getRespContentType();

    /**
     * <code>optional bytes contentByteArray = 10;</code>
     */
    boolean hasContentByteArray();
    /**
     * <code>optional bytes contentByteArray = 10;</code>
     */
    com.google.protobuf.ByteString getContentByteArray();

    /**
     * <code>required string content = 11;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 11;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 11;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code tutorial.message}
   */
  public static final class message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.message)
      messageOrBuilder {
    // Use message.newBuilder() to construct.
    private message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final message defaultInstance;
    public static message getDefaultInstance() {
      return defaultInstance;
    }

    public message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              Id_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.zq.kyb.core.model.ProtoMessage.message.MsgType value = com.zq.kyb.core.model.ProtoMessage.message.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              creator_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTime_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              actionPath_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              tokenStr_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              code_ = input.readInt32();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              com.zq.kyb.core.model.ProtoMessage.message.MsgFormat value = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                reqContentType_ = value;
              }
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              com.zq.kyb.core.model.ProtoMessage.message.MsgFormat value = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                bitField0_ |= 0x00000100;
                respContentType_ = value;
              }
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              contentByteArray_ = input.readBytes();
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              content_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zq.kyb.core.model.ProtoMessage.internal_static_tutorial_message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zq.kyb.core.model.ProtoMessage.internal_static_tutorial_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zq.kyb.core.model.ProtoMessage.message.class, com.zq.kyb.core.model.ProtoMessage.message.Builder.class);
    }

    public static com.google.protobuf.Parser<message> PARSER =
        new com.google.protobuf.AbstractParser<message>() {
      public message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code tutorial.message.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TYPE_NOTIFI = 0;</code>
       */
      TYPE_NOTIFI(0, 0),
      /**
       * <code>TYPE_REQ = 1;</code>
       */
      TYPE_REQ(1, 1),
      ;

      /**
       * <code>TYPE_NOTIFI = 0;</code>
       */
      public static final int TYPE_NOTIFI_VALUE = 0;
      /**
       * <code>TYPE_REQ = 1;</code>
       */
      public static final int TYPE_REQ_VALUE = 1;


      public final int getNumber() { return value; }

      public static MsgType valueOf(int value) {
        switch (value) {
          case 0: return TYPE_NOTIFI;
          case 1: return TYPE_REQ;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zq.kyb.core.model.ProtoMessage.message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.message.MsgType)
    }

    /**
     * Protobuf enum {@code tutorial.message.MsgFormat}
     */
    public enum MsgFormat
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>JSON = 0;</code>
       */
      JSON(0, 0),
      /**
       * <code>BYTE = 1;</code>
       */
      BYTE(1, 1),
      ;

      /**
       * <code>JSON = 0;</code>
       */
      public static final int JSON_VALUE = 0;
      /**
       * <code>BYTE = 1;</code>
       */
      public static final int BYTE_VALUE = 1;


      public final int getNumber() { return value; }

      public static MsgFormat valueOf(int value) {
        switch (value) {
          case 0: return JSON;
          case 1: return BYTE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgFormat>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgFormat>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgFormat>() {
              public MsgFormat findValueByNumber(int number) {
                return MsgFormat.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zq.kyb.core.model.ProtoMessage.message.getDescriptor().getEnumTypes().get(1);
      }

      private static final MsgFormat[] VALUES = values();

      public static MsgFormat valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgFormat(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.message.MsgFormat)
    }

    private int bitField0_;
    public static final int _ID_FIELD_NUMBER = 1;
    private java.lang.Object Id_;
    /**
     * <code>required string _id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string _id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = Id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          Id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string _id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = Id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private com.zq.kyb.core.model.ProtoMessage.message.MsgType type_;
    /**
     * <code>required .tutorial.message.MsgType type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .tutorial.message.MsgType type = 2;</code>
     */
    public com.zq.kyb.core.model.ProtoMessage.message.MsgType getType() {
      return type_;
    }

    public static final int CREATOR_FIELD_NUMBER = 3;
    private java.lang.Object creator_;
    /**
     * <code>optional string creator = 3;</code>
     */
    public boolean hasCreator() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string creator = 3;</code>
     */
    public java.lang.String getCreator() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          creator_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string creator = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      java.lang.Object ref = creator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 4;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int ACTIONPATH_FIELD_NUMBER = 5;
    private java.lang.Object actionPath_;
    /**
     * <code>required string actionPath = 5;</code>
     */
    public boolean hasActionPath() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string actionPath = 5;</code>
     */
    public java.lang.String getActionPath() {
      java.lang.Object ref = actionPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          actionPath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string actionPath = 5;</code>
     */
    public com.google.protobuf.ByteString
        getActionPathBytes() {
      java.lang.Object ref = actionPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENSTR_FIELD_NUMBER = 6;
    private java.lang.Object tokenStr_;
    /**
     * <code>optional string tokenStr = 6;</code>
     */
    public boolean hasTokenStr() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string tokenStr = 6;</code>
     */
    public java.lang.String getTokenStr() {
      java.lang.Object ref = tokenStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tokenStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tokenStr = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTokenStrBytes() {
      java.lang.Object ref = tokenStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 7;
    private int code_;
    /**
     * <code>required int32 code = 7;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 code = 7;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int REQCONTENTTYPE_FIELD_NUMBER = 8;
    private com.zq.kyb.core.model.ProtoMessage.message.MsgFormat reqContentType_;
    /**
     * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
     */
    public boolean hasReqContentType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
     */
    public com.zq.kyb.core.model.ProtoMessage.message.MsgFormat getReqContentType() {
      return reqContentType_;
    }

    public static final int RESPCONTENTTYPE_FIELD_NUMBER = 9;
    private com.zq.kyb.core.model.ProtoMessage.message.MsgFormat respContentType_;
    /**
     * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
     */
    public boolean hasRespContentType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
     */
    public com.zq.kyb.core.model.ProtoMessage.message.MsgFormat getRespContentType() {
      return respContentType_;
    }

    public static final int CONTENTBYTEARRAY_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString contentByteArray_;
    /**
     * <code>optional bytes contentByteArray = 10;</code>
     */
    public boolean hasContentByteArray() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional bytes contentByteArray = 10;</code>
     */
    public com.google.protobuf.ByteString getContentByteArray() {
      return contentByteArray_;
    }

    public static final int CONTENT_FIELD_NUMBER = 11;
    private java.lang.Object content_;
    /**
     * <code>required string content = 11;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required string content = 11;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 11;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      Id_ = "";
      type_ = com.zq.kyb.core.model.ProtoMessage.message.MsgType.TYPE_NOTIFI;
      creator_ = "";
      createTime_ = 0L;
      actionPath_ = "";
      tokenStr_ = "";
      code_ = 0;
      reqContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
      respContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
      contentByteArray_ = com.google.protobuf.ByteString.EMPTY;
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasActionPath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCreatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getActionPathBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTokenStrBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, code_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, reqContentType_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeEnum(9, respContentType_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, contentByteArray_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCreatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getActionPathBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTokenStrBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, code_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, reqContentType_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, respContentType_.getNumber());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, contentByteArray_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zq.kyb.core.model.ProtoMessage.message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zq.kyb.core.model.ProtoMessage.message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.message)
        com.zq.kyb.core.model.ProtoMessage.messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zq.kyb.core.model.ProtoMessage.internal_static_tutorial_message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zq.kyb.core.model.ProtoMessage.internal_static_tutorial_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zq.kyb.core.model.ProtoMessage.message.class, com.zq.kyb.core.model.ProtoMessage.message.Builder.class);
      }

      // Construct using com.zq.kyb.core.model.ProtoMessage.message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        Id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.zq.kyb.core.model.ProtoMessage.message.MsgType.TYPE_NOTIFI;
        bitField0_ = (bitField0_ & ~0x00000002);
        creator_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        actionPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        tokenStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        reqContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
        bitField0_ = (bitField0_ & ~0x00000080);
        respContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
        bitField0_ = (bitField0_ & ~0x00000100);
        contentByteArray_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zq.kyb.core.model.ProtoMessage.internal_static_tutorial_message_descriptor;
      }

      public com.zq.kyb.core.model.ProtoMessage.message getDefaultInstanceForType() {
        return com.zq.kyb.core.model.ProtoMessage.message.getDefaultInstance();
      }

      public com.zq.kyb.core.model.ProtoMessage.message build() {
        com.zq.kyb.core.model.ProtoMessage.message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zq.kyb.core.model.ProtoMessage.message buildPartial() {
        com.zq.kyb.core.model.ProtoMessage.message result = new com.zq.kyb.core.model.ProtoMessage.message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.Id_ = Id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.creator_ = creator_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.actionPath_ = actionPath_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tokenStr_ = tokenStr_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.reqContentType_ = reqContentType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.respContentType_ = respContentType_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.contentByteArray_ = contentByteArray_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zq.kyb.core.model.ProtoMessage.message) {
          return mergeFrom((com.zq.kyb.core.model.ProtoMessage.message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zq.kyb.core.model.ProtoMessage.message other) {
        if (other == com.zq.kyb.core.model.ProtoMessage.message.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          Id_ = other.Id_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCreator()) {
          bitField0_ |= 0x00000004;
          creator_ = other.creator_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasActionPath()) {
          bitField0_ |= 0x00000010;
          actionPath_ = other.actionPath_;
          onChanged();
        }
        if (other.hasTokenStr()) {
          bitField0_ |= 0x00000020;
          tokenStr_ = other.tokenStr_;
          onChanged();
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasReqContentType()) {
          setReqContentType(other.getReqContentType());
        }
        if (other.hasRespContentType()) {
          setRespContentType(other.getRespContentType());
        }
        if (other.hasContentByteArray()) {
          setContentByteArray(other.getContentByteArray());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000400;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasActionPath()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zq.kyb.core.model.ProtoMessage.message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zq.kyb.core.model.ProtoMessage.message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object Id_ = "";
      /**
       * <code>required string _id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string _id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = Id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            Id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string _id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = Id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string _id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        Id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string _id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        Id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string _id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        Id_ = value;
        onChanged();
        return this;
      }

      private com.zq.kyb.core.model.ProtoMessage.message.MsgType type_ = com.zq.kyb.core.model.ProtoMessage.message.MsgType.TYPE_NOTIFI;
      /**
       * <code>required .tutorial.message.MsgType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .tutorial.message.MsgType type = 2;</code>
       */
      public com.zq.kyb.core.model.ProtoMessage.message.MsgType getType() {
        return type_;
      }
      /**
       * <code>required .tutorial.message.MsgType type = 2;</code>
       */
      public Builder setType(com.zq.kyb.core.model.ProtoMessage.message.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .tutorial.message.MsgType type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.zq.kyb.core.model.ProtoMessage.message.MsgType.TYPE_NOTIFI;
        onChanged();
        return this;
      }

      private java.lang.Object creator_ = "";
      /**
       * <code>optional string creator = 3;</code>
       */
      public boolean hasCreator() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string creator = 3;</code>
       */
      public java.lang.String getCreator() {
        java.lang.Object ref = creator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            creator_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string creator = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        java.lang.Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string creator = 3;</code>
       */
      public Builder setCreator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 3;</code>
       */
      public Builder clearCreator() {
        bitField0_ = (bitField0_ & ~0x00000004);
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>optional string creator = 3;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creator_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000008;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object actionPath_ = "";
      /**
       * <code>required string actionPath = 5;</code>
       */
      public boolean hasActionPath() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string actionPath = 5;</code>
       */
      public java.lang.String getActionPath() {
        java.lang.Object ref = actionPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            actionPath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string actionPath = 5;</code>
       */
      public com.google.protobuf.ByteString
          getActionPathBytes() {
        java.lang.Object ref = actionPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string actionPath = 5;</code>
       */
      public Builder setActionPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        actionPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string actionPath = 5;</code>
       */
      public Builder clearActionPath() {
        bitField0_ = (bitField0_ & ~0x00000010);
        actionPath_ = getDefaultInstance().getActionPath();
        onChanged();
        return this;
      }
      /**
       * <code>required string actionPath = 5;</code>
       */
      public Builder setActionPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        actionPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenStr_ = "";
      /**
       * <code>optional string tokenStr = 6;</code>
       */
      public boolean hasTokenStr() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string tokenStr = 6;</code>
       */
      public java.lang.String getTokenStr() {
        java.lang.Object ref = tokenStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tokenStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tokenStr = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTokenStrBytes() {
        java.lang.Object ref = tokenStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tokenStr = 6;</code>
       */
      public Builder setTokenStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        tokenStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tokenStr = 6;</code>
       */
      public Builder clearTokenStr() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tokenStr_ = getDefaultInstance().getTokenStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tokenStr = 6;</code>
       */
      public Builder setTokenStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        tokenStr_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>required int32 code = 7;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 code = 7;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 7;</code>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000040;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 7;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        code_ = 0;
        onChanged();
        return this;
      }

      private com.zq.kyb.core.model.ProtoMessage.message.MsgFormat reqContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
      /**
       * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
       */
      public boolean hasReqContentType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
       */
      public com.zq.kyb.core.model.ProtoMessage.message.MsgFormat getReqContentType() {
        return reqContentType_;
      }
      /**
       * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
       */
      public Builder setReqContentType(com.zq.kyb.core.model.ProtoMessage.message.MsgFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        reqContentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.message.MsgFormat reqContentType = 8 [default = JSON];</code>
       */
      public Builder clearReqContentType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        reqContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
        onChanged();
        return this;
      }

      private com.zq.kyb.core.model.ProtoMessage.message.MsgFormat respContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
      /**
       * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
       */
      public boolean hasRespContentType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
       */
      public com.zq.kyb.core.model.ProtoMessage.message.MsgFormat getRespContentType() {
        return respContentType_;
      }
      /**
       * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
       */
      public Builder setRespContentType(com.zq.kyb.core.model.ProtoMessage.message.MsgFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000100;
        respContentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.message.MsgFormat respContentType = 9 [default = JSON];</code>
       */
      public Builder clearRespContentType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        respContentType_ = com.zq.kyb.core.model.ProtoMessage.message.MsgFormat.JSON;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contentByteArray_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes contentByteArray = 10;</code>
       */
      public boolean hasContentByteArray() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional bytes contentByteArray = 10;</code>
       */
      public com.google.protobuf.ByteString getContentByteArray() {
        return contentByteArray_;
      }
      /**
       * <code>optional bytes contentByteArray = 10;</code>
       */
      public Builder setContentByteArray(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        contentByteArray_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes contentByteArray = 10;</code>
       */
      public Builder clearContentByteArray() {
        bitField0_ = (bitField0_ & ~0x00000200);
        contentByteArray_ = getDefaultInstance().getContentByteArray();
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 11;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required string content = 11;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 11;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 11;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 11;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000400);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 11;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.message)
    }

    static {
      defaultInstance = new message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/java/tutorial/message.proto\022\010" +
      "tutorial\"\205\003\n\007message\022\013\n\003_id\030\001 \002(\t\022\'\n\004typ" +
      "e\030\002 \002(\0162\031.tutorial.message.MsgType\022\017\n\007cr" +
      "eator\030\003 \001(\t\022\022\n\ncreateTime\030\004 \001(\003\022\022\n\nactio" +
      "nPath\030\005 \002(\t\022\020\n\010tokenStr\030\006 \001(\t\022\014\n\004code\030\007 " +
      "\002(\005\0229\n\016reqContentType\030\010 \001(\0162\033.tutorial.m" +
      "essage.MsgFormat:\004JSON\022:\n\017respContentTyp" +
      "e\030\t \001(\0162\033.tutorial.message.MsgFormat:\004JS" +
      "ON\022\030\n\020contentByteArray\030\n \001(\014\022\017\n\007content\030" +
      "\013 \002(\t\"(\n\007MsgType\022\017\n\013TYPE_NOTIFI\020\000\022\014\n\010TYP",
      "E_REQ\020\001\"\037\n\tMsgFormat\022\010\n\004JSON\020\000\022\010\n\004BYTE\020\001" +
      "B%\n\025com.zq.kyb.core.modelB\014ProtoMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_message_descriptor,
        new java.lang.String[] { "Id", "Type", "Creator", "CreateTime", "ActionPath", "TokenStr", "Code", "ReqContentType", "RespContentType", "ContentByteArray", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
